-- v288: public edition API — DEFERRED by maintainer decision (2026-10-05).
--
-- The public, unauthenticated read surface for the edition repository is NOT
-- shipping yet. The eventual design is a private API for signed-in users plus
-- a read-only public API; until that split is designed, there is no public
-- endpoint and no anonymous access to the repository tables.
--
-- This file intentionally applies nothing. It reserves the v288 number so the
-- migration sequence stays coherent (v288 shipped the admin moderation lab
-- and the APP_VERSION/SW cache bump; the API itself waits).
--
-- When the public API is designed, add its grants + policies in a new
-- migration (e.g. v289_public_edition_api.sql) — do not resurrect the
-- unauthenticated CORS-open draft that lived here.
select 1;
